version: '3.4'

services:
  cloupard_api:
    ports:
      - "5050:8080"
    networks: 
      - shared_cloupard
    restart: always
    env_file:
      - env.api
  
  cloupard_mvc:
    ports:
      - "5051:8080"
    networks:
      - shared_cloupard
    restart: always
    env_file:
      - env.mvc
  
  cloupard_sqldata:
    environment:
      - SA_PASSWORD=4i-sY0v>av,1A0
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    restart: always
    networks: 
      - shared_cloupard
    volumes:
      - ~/.cloupard/mssql/data/:/var/lib/mssql/data


networks:
  shared_cloupard:
    driver: bridge