version: '3.4'

services: 
  cloupard_api:
    image: ${DOCKER_REGISTRY-}cloupard_api
    build:
      context: .
      dockerfile: src/Presentation/Cloupard.Api/Dockerfile
  
  cloupard_mvc:
    image: ${DOCKER_REGISTRY-}cloupard_mvc
    build:
      context: .
      dockerfile: src/Presentation/Cloupard.MVC/Dockerfile
    depends_on: 
      - cloupard_api